### ISSUE TITLE
Trap file when installing a rpm file

### ISSUE THREAD

**Issue by Tellie** [bitwiseworks/sqlite-os2#1] opened 2019-04-05 16:52 UTC
Hi,

When i try todo rpm install libdvdread i get a trp file.
I will attach the debug trp file

**Comment by Tellie** [comment] 2019-04-05 16:54
The trp file @ https://pastebin.com/53CjS6D9

**Comment by Tellie** [comment] 2019-04-09 18:03
I upload a new trp file...

https://pastebin.com/KNqfdzdi

**Comment by dmik** [comment] 2019-04-09 18:05
Ok, both traps look like stack corruption to me so, unfortunately, not very informative. I think SQLite debugging should be deployed here somehow.

**Comment by dmik** [comment] 2019-06-28 19:45
Digging heavily into yum code, I've tracked it down to this minimal python code that makes it trap (requires yum files located in `/@unixroot/var/lib/yum/history` but doesn't involve yum itself and doesn't corrupt these files):

```python
import os, glob
import sqlite3

db_path = '/@unixroot/var/lib/yum/history'

DBs = glob.glob('%s/history-*-*-*.sqlite' % db_path)
db_file = None
for d in reversed(sorted(DBs)):
    fname = os.path.basename(d)
    fname = fname[len("history-"):-len(".sqlite")]
    pieces = fname.split('-', 4)
    if len(pieces) != 3:
        continue
    try:
        map(int, pieces)
    except ValueError:
        continue

    db_date = '%s-%s-%s' % (pieces[0], pieces[1], pieces[2])
    db_file = d
    break

print 'db_file', db_file

conn = sqlite3.connect(db_file)
cur = conn.cursor()
cur.execute("PRAGMA locking_mode = EXCLUSIVE")

sql = """SELECT tid,
                         trans_beg.timestamp AS beg_ts,
                         trans_beg.rpmdb_version AS beg_rv,
                         trans_end.timestamp AS end_ts,
                         trans_end.rpmdb_version AS end_rv,
                         loginuid, return_code
                  FROM trans_beg JOIN trans_end USING(tid) ORDER BY beg_ts DESC, tid ASC LIMIT 1"""

cur.execute(sql)

for row in cur:
	print row
```

The first part of the script prior to `print 'db_file', db_file` is irrelevant, it simply locates the sqlite file of your yum installation. It crashes while executing `cur.execute`, i.e. right after printing the `db_file` value. When using the older sqlite3 DLL, it doesn't crash and the output is like this:
```
db_file /@unixroot/var/lib/yum/history/history-2017-02-02.sqlite
(186, 1561750455, u'262:f460c05cb1a9c71e50bf9cd7c38396dd5c4d32f5', 1561750456, u'262:f460c05cb1a9c71e50bf9cd7c38396dd5c4d32f5', None, 0)
```
So, apparently the new sqlite3 DLL somehow screws up this SQL query. The question is if it's sqlite3 python bindings or sqlite3 itself. In order to answer this question, the same query needs to be run from C.

**Comment by dmik** [comment] 2019-06-28 20:07
It somehow feels related to the amount of data in the table. The very same query works fine on a small test table. And, vise versa, on the real table (which seems to contain around 200 rows) even a very simple query like `SELECT * from trans_beg` fails. So may be it's some memory allocation which blows up.

**Comment by dmik** [comment] 2019-07-01 20:02
Thorough debugging shows that the following course of actions makes it crash:
![Снимок экрана 2019-07-01 в 22 51 12](https://user-images.githubusercontent.com/900726/60462725-c05bbe00-9c52-11e9-811e-331727526652.png)

What `fsNativeSetEAs` does is this:

![Снимок экрана 2019-07-01 в 22 52 53](https://user-images.githubusercontent.com/900726/60462806-fb5df180-9c52-11e9-9b8d-0f8d068262b8.png)

I.e. it just calls `DosOpenL` (a 64-bit aware version of `DosOpen`) in an attempt to change EAs of the journal file of the SQL database in a request of `fchown(root, root)` on it from sqlite. Currently, I have no idea why this call fails inside DOSCALLS. Arguments to it look pretty legal from the debugger (the file name is a valid string etc). And a simple C test case calling `fchown` on the very same file (that causes the very same code to execute in both LIBCN0 and DOSCALLS) works just fine. Deeper debugging is needed.

Note that disabling this `fchown` call in sqlite makes it not crash and yum also works fine when reinstalling packages at least. But it's still important to find out why it crashes because this may be an indicator of some bigger problem in LIBCN0 or in python.

**Comment by dmik** [comment] 2019-07-01 20:44
Some more details: this `fchown` call operates on a file handle opened in O_RDONLY mode. `fsNativeSetEAs` in LIBC tries to cheat here by opening the file again in an attempt to get a writable file handle and set EAs on it instead. Comments indicate that this should work but in a simple test case using only `fchown` it still doesn't — `fchown` doesn't crash there but returns -1 and EINVAL (22). The reason of the crash is still not known but apparently, this part in LIBC has some issues (and I recall other similar problems related to Unix file bits and r/o files).

**Comment by dmik** [comment] 2019-07-01 21:42
I think I found out what's wrong. LIBC itself uses custom entry points for DosOpenL and some other calls (`__libc_gpfnDosOpenL` and friends) in some places including the `fchown` code path. These entry points are resolved at LIBC init time directly from DOSCALLS by `DosQueryProcAddr`. However, `DosOpenL` (as well as `DosOpen` and many others) is not high memory safe. And the string coming to this API is in fact in high memory (placed there by LIBC itself — when creating a new internal FH record for the file descriptor in `open`). Funny enough, LIBC provides safe wrappers for such calls, including `DosOpenL`. But given the direct resolve, this wrapper is simply not used.

I'm not sure why these direct resolves are still there — perhaps they are back from the days when LIBOS2.LIB lacked these "secret" DOSCALLS imports. Anyway, just replacing `__libc_gpfnDosOpenL` with `DosOpen` makes everything work as it should. Meaning that the R/O file is successfully reopened for writing indeed so that `fchown` succeeds.

I will try to reproduce it in a C test case to be 100% sure.

**Comment by dmik** [comment] 2019-07-02 15:37
Note that I've moved this to LIBC and fixed it there already. Sqilte works fine with the new LIBC w/o any fixes on the sqlite side. So I'm closing this in favor of that ticket.

**Closed as completed by dmik** 2019-07-02 15:37 UTC
